title: Suspicious Network Download Inside Container
id: 33333333-4444-5555-6666-777777777774
logsource:
    product: docker
    category: container_logs
detection:
    selection:
        line|contains:
            - 'wget'
            - 'curl'
    condition: selection
level: high
