title: Docker Socket Mounted to Container
id: 33333333-4444-5555-6666-777777777772
logsource:
    product: docker
    category: container_logs
detection:
    selection:
        line|contains:
            - 'docker.sock'
    condition: selection
level: critical
