title: Container Escape Attempt via Nsenter
id: 33333333-4444-5555-6666-777777777775
logsource:
    product: linux
    category: process_creation
detection:
    selection:
        CommandLine|contains:
            - 'nsenter -t 1 -m -u -n -i sh'
            - 'nsenter --target 1 --mount'
    condition: selection
level: critical
