title: OWASP - Vulnerable Component Exploitation (Shell spawned by App)
id: 66666666-7777-8888-9999-000000000002
logsource:
    product: docker
    category: container_logs
detection:
    selection:
        line|contains:
            - '/bin/bash'
            - '/bin/sh'
            - '/bin/dash'
    condition: selection
level: critical
