title: OWASP - Security Misconfiguration (Sensitive Host Mount)
id: 66666666-7777-8888-9999-000000000001
logsource:
    product: docker
    category: container_logs
detection:
    selection:
        line|contains:
            - ':/etc'
            - ':/root'
            - ':/boot'
    condition: selection
level: high
