title: OWASP - Vulnerable Component Exploitation (Shell spawned by App)
id: 66666666-7777-8888-9999-000000000002
logsource:
    product: linux
    category: process_creation
detection:
    selection:
        ParentImage|endswith:
            - '/java'
            - '/node'
            - '/python'
            - '/ruby'
        Image|endswith:
            - '/bash'
            - '/sh'
            - '/dash'
    condition: selection
level: critical
