name: Deploy Splunk Rules via REST API

on:
  push:
    branches: [ main ]
    paths:
      - 'splunk/**'

jobs:
  deploy-splunk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
      - run: pip install -r requirements.txt
      - name: Execute Splunk Deployment
        env:
          SPLUNK_HOST: ${{ secrets.SPLUNK_HOST }}
          SPLUNK_PORT: ${{ secrets.SPLUNK_PORT }}
          SPLUNK_TOKEN: ${{ secrets.SPLUNK_TOKEN }}
        run: python splunk/deploy_splunk.py
