name: Deploy Rules to Splunk

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Send Rule to Splunk REST API
        run: |
          echo "Splunk REST API vasitəsilə alert yaradılır..."
          
          curl -k -u "\({{ secrets.SPLUNK_USER }}:\){{ secrets.SPLUNK_PASSWORD }}" \
            https://\({{ secrets.SPLUNK_HOST }}:\){{ secrets.SPLUNK_PORT }}/servicesNS/nobody/search/saved/searches \
            -d name="OWASP_OS_Command_Injection" \
            -d search="index=* | eval decoded_uri=urldecode(uri) | rex field=decoded_uri \"(?whoami|id|cat)\" | where isnotnull(os_command)" \
            -d is_scheduled=1 \
            -d cron_schedule="*/5 * * * *"
